packages:
  - apps/*
  - docs/*
  - configs/*
  - scripts/*

allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false

catalog:
  vite: ^6.2.0
  vue: ^3.5.13
  vue-router: ^4.5.0
  code-inspector-plugin: ^1.2.10
  '@tnnevol/deploy': ^1.0.12
  postcss: ^8.5.6
